name: isleg_ecommerce
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  go_router: ^13.1.0
  flutter_iconly: ^1.0.2
  cupertino_icons: ^1.0.6
  dio:
  cached_network_image: ^3.3.1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
  fonts:
    - family: TT Norms Pro Medium
      fonts:
        - asset: assets/fonts/TT Norms Pro Medium.otf
